classificacao/classificacao/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import urls as dashboard_urls
from class_informacao import urls as class_urls
from desclass_informacao import urls as desclass_urls
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include(dashboard_urls)),
    path('admin/', admin.site.urls),
    path('', include(class_urls)),
    path('', include(desclass_urls)),
]

classificacao/dashboard/urls.py
from django.urls import path
from .views import home, my_logout, login_restrito, logout


urlpatterns = [
    path('', home, name="home"),
    path('login/', login_restrito, name="login"),
    path('logout/', my_logout, name="logout"),
]

classificacao/desclass_informacao/urls.py
from django.urls import path
from .views import  desclassificacao, get_nic


urlpatterns = [
    path('desclassificacao/', desclassificacao, name="desclassificacao"),
    path('procura_nic/', get_nic, name="procura_nic"),
]

classificacao/desclass_informacao/models.py
from django.db import models

# Create your models here.


class fund_desclassificacao(models.Model):
    descricao = models.CharField(max_length=250)
    def __str__(self):
        return self.descricao

classificacao/desclass_informacao/forms.py
from django import forms
from django.forms import ModelForm

from class_informacao.models import classificacao


class procuraNIC(forms.Form):
    nic = forms.CharField(max_length=30)

class visualisar_desclass(ModelForm):
    # TODO precisa verificar se é preciso criar um formulário para carregar tais informações
        class Meta:
            model = classificacao
            fields = '__all__'

classificacao/desclass_informacao/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from .forms import procuraNIC, visualisar_desclass
from .models import fund_desclassificacao

@login_required(login_url="/login/")
def get_nic(request):
    form = procuraNIC(request.POST or None)
    if form.is_valid():
        # TODO precisa fatiar o NIC para salvar cada parte dele no banco
        # TODO Enviar o NIC pela url para ser carregada no form
        return redirect('desclassificacao')
    return render(request, 'procura_nic.html', {'form': form})


@login_required(login_url="/login/")
def desclassificacao(request):
        # TODO Precisa receber o NIC da pagina anterior, buscar no banco
        # TODO e popular o formulario com as informações.
    fund_desclassif = fund_desclassificacao.objects.order_by('id')

    return render(request, 'desclassificacao.html', {'fund_desclassif': fund_desclassif})

classificacao/desclass_informacao/templates/desclassificacao.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block css %}

{% endblock %}

{% block breadcrumb %}
   	<li class="active">desclassificação</li>
{% endblock breadcrumb %}

{% block title_page %}

{% endblock title_page %}

{% block titulo %}

{% endblock titulo %}

{% block titulo_pagina %}

{% endblock titulo_pagina %}

{% block content %}
    <div class="col">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3>Desclassificação</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-sm-3">
                        <label for="und_gestora">Unidade gestora:</label>
                        <input type="text" style="" id="und_gestora" name="und_gestora" value="CGE" disabled/>
                    </div>
                    <div class="col-sm-3">
                        <label for="id_nic">NIC:</label>
                        <input type="text" style="" id="id_nic" value="123456121231234" disabled/>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-2">
                        <label for="assunto">Assunto:</label>
    <!--                    <input type="text" style="" id="assunto" name="assunto" value="Informações do documento." disabled/>-->
                        <textarea id="assunto" name="assunto" rows="5" disabled>Informações do documento.</textarea>
                    </div>
                    <div class="col-sm-2">
                        <label for="razao_classif">Razão da Classificação:</label>
    <!--                    <input type="text" style="" id="razao_classif" name="razao_classif" value="Razões para o documento ser desclassificado." disabled/>-->
                        <textarea id="razao_classif" name="razao_classif" rows="5" disabled>Razões para o documento ser desclassificado.</textarea>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="grau_sigilo">Grau de Sigilo:</label>
                        <input type="text" style="" id="grau_sigilo" name="grau_sigilo" value="Secreto" disabled/>
                    </div>
                    <div class="col-sm-3">
                        <label for="data_prod">Data de Produção:</label>
                        <input type="date" style="" id="data_prod" value="2019-02-05" disabled/>
                    </div>
                    <div class="col-sm-3">
                        <label for="prazo">Prazo:</label>
                        <input type="text" style="" id="prazo" value="5 anos" disabled/>
                    </div>
                    <div class="col-sm-3">
                        <label for="data_classif">Data da Classificação:</label>
                        <input type="date" style="" id="data_classif" value="2019-05-06" disabled/>
                    </div>
                    <div class="col-sm-3">
                        <label for="prazo_final">Prazo final da Classificação:</label>
                        <input type="date" style="" id="prazo_final" value="2024-02-05" disabled/>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="autoridade_class">Autoridade classificadora:</label>
                        <input type="text" style="" id="autoridade_class" name="autoridade_class" value="Autoridade X" disabled/>
                    </div>
                    <div class="col-sm-3">
                        <label for="autoridade_ratif">Autoridade Ratificadora:</label>
                        <input type="text" style="" id="autoridade_ratif" value="Senhora X" disabled/>
                    </div>
                    <div class="col-sm-3">
                        <label for="autoridade_desclass">Autoridade desclassificadora:</label>
                        <input type="text" style="" id="autoridade_desclass" name="autoridade_desclass" value="Autoridade A" />
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="fundamento_desclass">Fundamento da Desclassificação:</label>
                        <select id="fundamento_desclass">
                            {% for fundament in fund_desclassif %}
                                <option>{{fundament.descricao}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-ok"></span> Save
                    </button>
                    <a href="{% url 'home' %}" class="btn btn-default">Cancel</a>
                </div>
                <input type="text" style="display:none;" id="textInputId" name="someName"/>

            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}

{% endblock %}

classificacao/desclass_informacao/templates/procura_nic.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block css %}

{% endblock %}

{% block breadcrumb %}
   	<li class="active">desclassificação</li>
{% endblock breadcrumb %}

{% block title_page %}

{% endblock title_page %}

{% block titulo %}

{% endblock titulo %}

{% block titulo_pagina %}

{% endblock titulo_pagina %}

{% block content %}
    <div class="container ">
        <div class="col">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="row-sm-8">
                        <h2>{{field.label}}:</h2>
                        <h4>Digite o NIC da informação que deseja desclassificar.</h4>
                        {% render_field field class="form-group row-sm-8" %}
                    </div>
                {% endfor %}
                <div class="row-sm-8">
                    <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-search"></span>
                    </button>
                    <a href="{% url 'home' %}" class="btn btn-default btn-sm">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

{% block js %}
<!--    <script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>-->
{% endblock %}