classificacao/class_informacao/urls.py
from django.urls import path
from .views import classificacao, desclassificacao, reclassificacao


urlpatterns = [
    path('classificacao/', classificacao, name="classificacao"),
    # path('desclassificacao/', desclassificacao, name="desclassificacao"),
    path('reclassificacao/', reclassificacao, name="reclassificacao"),
]

classificacao/classificacao/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import urls as dashboard_urls
from class_informacao import urls as class_urls
from desclass_informacao import urls as desclass_urls
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include(dashboard_urls)),
    path('admin/', admin.site.urls),
    path('', include(class_urls)),
    path('', include(desclass_urls)),
]

classificacao/dashboard/urls.py
from django.urls import path
from .views import home, my_logout, login_restrito, logout


urlpatterns = [
    path('', home, name="home"),
    path('login/', login_restrito, name="login"),
    path('logout/', my_logout, name="logout"),
]

classificacao/class_informacao/models.py
from django.db import models

# Create your models here.
class grau_sigilo(models.Model):
    descricao = models.CharField(max_length=150)
    qnt_ano = models.IntegerField()
    cod = models.IntegerField()
    def __str__(self):
        return self.descricao


class fund_classificacao(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=250)
    def __str__(self):
        return self.descricao


class und_gestora(models.Model):
    cod = models.IntegerField()
    sigla = models.CharField(max_length=10)
    descricao = models.CharField(max_length=150)
    def __str__(self):
        return self.descricao

class tipo_doc(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=250)
    def __str__(self):
        return self.nome


class NIC(models.Model):
    cod_und_gestora = models.ForeignKey(und_gestora, on_delete=models.CASCADE)
    id_tipo_doc = models.ForeignKey(tipo_doc, on_delete=models.CASCADE)
    ano = models.IntegerField()
    numero = models.CharField(max_length=30)

class classificacao(models.Model):
    und_gestora = models.ForeignKey(und_gestora, on_delete=models.CASCADE)
    nic = models.ForeignKey(NIC, on_delete=models.CASCADE)
    assunto = models.TextField()
    grau_sigilo = models.ForeignKey(grau_sigilo, on_delete=models.CASCADE)
    tipo_doc = models.ForeignKey(tipo_doc, on_delete=models.CASCADE)
    data_doc = models.DateField()
    fund_classificacao = models.ForeignKey(fund_classificacao, on_delete=models.CASCADE)
    razao_calssf = models.TextField()
    data_classf_doc = models.DateField()
    autoridade_classf = models.CharField(max_length=150)
    autoridade_ratificadora = models.CharField(max_length=150)
    prazo_sigilo = models.IntegerField()
    prazo_final = models.DateField()

classificacao/class_informacao/forms.py
from django import forms
from django.forms import ModelForm

from .models import classificacao


class ClassificacaoForm (ModelForm):
    class Meta:
        model = classificacao
        exclude = ['nic']

classificacao/class_informacao/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from .forms import ClassificacaoForm


# Create your views here.
@login_required(login_url="/login/")
def classificacao(request):
    form = ClassificacaoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('home')
    return render(request, 'classificacao.html', {'form': form})


@login_required(login_url="/login/")
def desclassificacao(request):
    return render(request, 'desclassificacao.html')


@login_required(login_url="/login/")
def reclassificacao(request):
    return render(request, 'reclassificacao.html')

classificacao/class_informacao/templates/classificacao.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block css %}

{% endblock %}

{% block breadcrumb %}
   	<li class="active">classificação</li>
{% endblock breadcrumb %}

{% block title_page %}

{% endblock title_page %}

{% block titulo %}

{% endblock titulo %}

{% block titulo_pagina %}

{% endblock titulo_pagina %}

{% block content %}
    <div class="col">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3>Classificação</h3>
            </div>
            <div class="box-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        <!--                    {{ field|add_class:'form-control' }}-->
                            {% render_field field class="form-control" %}
                            {% for error in field.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endfor %}
            </div>
            <div class="box-footer">
                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-ok"></span> Save
                    </button>
                    <a href="{% url 'home' %}" class="btn btn-default">Cancel</a>
                </div>
                   <input type="text" style="display:none;" id="textInputId" name="someName"/>
                </form>
            </div>
    </div>
{% endblock content %}

{% block js %}
        <script type="text/javascript">
            $(document).ready(function(){
                $("#id_grau_sigilo").change(function(){
                    if($(this).val() == 1){
                        $("#id_prazo_sigilo").val(5);
                    }if($(this).val() == 2){
                        $("#id_prazo_sigilo").val(10);
                    }if($(this).val() == 3){
                        $("#id_prazo_sigilo").val(20);
                    }
                });
            });
        </script>
{% endblock %}